Rename typed-frames to iskra
VirtusLab/iskra pull request #9
Opened 2022-08-24 15:33 UTC by romanowski

2022-08-24 16:27 UTC, tgodzik commented
Isn't it too polish? :sweat_smile:

2022-08-25 07:45 UTC, prolativ requested changes

2022-08-25 07:45 UTC, prolativ commented on README.md
>  TypedFrames is a Scala 3 wrapper around Apache Spark API which allows writing typesafe and boilerplate-free but still efficient Spark code.
```suggestion
Iskra is a Scala 3 wrapper around Apache Spark API which allows writing typesafe and boilerplate-free but still efficient Spark code.
```

2022-08-25 07:51 UTC, prolativ commented
Two other things to be done:
1) Update `publish-conf.scala`
2) Rename packages
The second point could be done in a separate PR as well

2022-08-25 07:58 UTC, prolativ commented
> 



> Isn't it too polish? 😅

Wasn't the previous name too English? 😉 

 
--

2022-08-25 08:55 UTC, tgodzik commented
Maybe let's polish it up a bit more. I think `trzcina` is a great name :sweat_smile:

2022-08-30 14:21 UTC, prolativ approved these changes

2022-08-30 14:21 UTC, merged